trend_analysis_task:
  description: >
    Conduct an in-depth analysis of current market trends.
    Gather and summarize the 10 most relevant trends related to business expansion in 2024.
  expected_output: >
    A list with 10 bullet points summarizing the key market trends relevant to business expansion.
  agent: trend_researcher

competitor_analysis_task:
  description: >
    Analyze competitors in the market.
    Identify their strengths, weaknesses, and areas where the company can outperform them.
  expected_output: >
    A detailed markdown report listing competitors, their key strengths, weaknesses, and potential market gaps.
  agent: competitor_analyst

audience_insights_task:
  description: >
    Analyze audience demographics and behaviors to identify potential new markets or segments.
    Suggest actionable recommendations for expanding the audience reach.
  expected_output: >
    A list of audience insights and recommendations formatted as markdown.
  agent: audience_insights_specialist
